name             'lxc'
maintainer       'Atalanta Systems Engineering' 
maintainer_email 'cookbooks@atalanta-systems.com'
license          'All rights reserved'
description      'Installs/Configures lxc'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.0'
depends		 'network'
depends		 'build-essential'
depends		 'ark'
