default['lxc']['container_path'] = "/var/lxc"
default['lxc']['template'] = "c6-lxc-template.tar.gz"
default['lxc']['template_path'] = "https://s3-eu-west-1.amazonaws.com/c6lxc"
default['lxc']['network'] = "10.1.1.0/24"
default['lxc']['domain'] =  "uat.pcfg.biz"
default['lxc']['nameserver'] = "10.1.1.103"
